{% set version = "0.19.0" %}
{% set sha256 = "39065966a0a691af268014f65ab5d41ecd840a7630861bec1bfb9f14a0f24e47" %}

package:
  name: numcosmo
  version: {{ version }}

source:
  url: https://github.com/NumCosmo/NumCosmo/releases/download/v{{ version }}/numcosmo-{{ version }}.tar.xz 
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  skip: true  # [python_impl == 'pypy']
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - meson
    - ninja
    - pkg-config
    - pytest
    - pygobject
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - gobject-introspection
    - libblas                # [build_platform != target_platform]
    - libcblas               # [build_platform != target_platform]
    - liblapack              # [build_platform != target_platform]
    - glib                   # [build_platform != target_platform]
    - gsl                    # [build_platform != target_platform]
    - gmp                    # [build_platform != target_platform]
    - mpfr                   # [build_platform != target_platform]
    - fftw                   # [build_platform != target_platform]
    - nlopt                  # [build_platform != target_platform]
    - cfitsio                # [build_platform != target_platform]
    - arb                    # [build_platform != target_platform]
    - hdf5                   # [build_platform != target_platform]
    - libfyaml               # [build_platform != target_platform]
  host:
    - libblas
    - libcblas
    - liblapack
    - glib
    - gsl
    - gmp
    - mpfr
    - fftw
    - nlopt
    - cfitsio
    - arb
    - hdf5
    - libfyaml
    - python
    - pytest
    - pygobject
  run:
    - libcurl
    - fftw
    - nlopt
    - cfitsio
    - pygobject
    - numpy
    - matplotlib-base
    - zlib
    - python

test:
  requires:
    - pygobject
  commands:
    - test -f ${PREFIX}/lib/libnumcosmo{{ SHLIB_EXT }}   # [not win]
    - $PYTHON ${PREFIX}/share/numcosmo-{{ version }}/examples/example_simple.py

about:
  home: https://numcosmo.github.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'NumCosmo is a free software C library whose main purposes are to test cosmological models using observational data and to provide a set of tools to perform cosmological calculations.'

extra:
  recipe-maintainers:
    - vitenti
