{% set version = "0.14.2" %}
{% set sha256 = "6143484fa7008a2ce80fbd2a91400df8d24b303c435d4d91e38c339d74ecbc82" %}

package:
  name: numcosmo
  version: {{ version }}

source:
  url: https://github.com/NumCosmo/NumCosmo/releases/download/v{{ version }}/numcosmo-{{ version }}.tar.gz 
  sha256: {{ sha256 }}

build:
  number: 9
  skip: True  # [win]
  detect_binary_files_with_prefix: True
  run_exports:
    - {{ pin_subpackage('numcosmo', max_pin='x.x') }}

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - gobject-introspection
    - libblas
    - libcblas
    - liblapack
    - glib
    - gsl
    - gmp
    - mpfr
    - fftw
    - nlopt
    - cfitsio
    - arb
    - hdf5
  run:
    - libcurl
    - fftw
    - nlopt
    - cfitsio
    - pygobject
    - numpy
    - matplotlib-base
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libnumcosmo{{ SHLIB_EXT }}   # [not win]
    - $PYTHON ${PREFIX}/share/numcosmo-{{ version }}/examples/example_simple.py

about:
  home: https://numcosmo.github.io/
  license: GPL-3.0
  license_file: COPYING
  summary: 'NumCosmo is a free software C library whose main purposes are to test cosmological models using observational data and to provide a set of tools to perform cosmological calculations.'

extra:
  recipe-maintainers:
    - vitenti
