{% set version = "0.14.2" %}
{% set sha256 = "be448a6e7d9c68a91af9ab60140cafe99212656e21a72bdbbeabc1e54de67e93" %}

package:
  name: numcosmo
  version: {{ version }}

source:
  url: https://github.com/NumCosmo/NumCosmo/releases/download/v{{ version }}/numcosmo-{{ version }}.tar.gz 
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - glib
    - gsl
    - gmp
    - mpfr
    - sundials
    - fftw
    - nlopt
    - cfitsio
    - openblas
    - lapack
    - arb
    - gobject-introspection
  run:
    - python
    - glib
    - gsl
    - gmp
    - mpfr
    - sundials
    - fftw
    - nlopt
    - cfitsio
    - openblas
    - lapack
    - arb
    - pygobject
    - numpy
    - matplotlib

test:
  commands:
    - test -f ${PREFIX}/lib/libnumcosmo{{ SHLIB_EXT }}   # [not win]
    - $PYTHON ${PREFIX}/share/numcosmo-{{ version }}/examples/example_simple.py

about:
  home: https://numcosmo.github.io/
  license: GPL-3.0
  license_file: COPYING
  summary: 'NumCosmo is a free software C library whose main purposes are to test cosmological models using observational data and to provide a set of tools to perform cosmological calculations.'

extra:
  recipe-maintainers:
    - vitenti
