{% set version = "0.17.0" %}
{% set sha256 = "91bd9d6a9475a6fc5c2eaff4b647c2230a993ea7790b1fb9059d32adb95bea65" %}

package:
  name: numcosmo
  version: {{ version }}

source:
  url: https://github.com/NumCosmo/NumCosmo/releases/download/v{{ version }}/numcosmo-{{ version }}.tar.gz 
  sha256: {{ sha256 }}

build:
  number: 9
  skip: True  # [win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - make  # [unix]
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - gobject-introspection
    - libblas
    - libcblas
    - liblapack
    - glib
    - gsl
    - gmp
    - mpfr
    - fftw
    - nlopt
    - cfitsio
    - arb
    - hdf5
    - libfyaml
    - python
    - pytest
    - pygobject
  run:
    - libcurl
    - fftw
    - nlopt
    - cfitsio
    - pygobject
    - numpy
    - matplotlib-base
    - zlib
    - python

test:
  commands:
    - test -f ${PREFIX}/lib/libnumcosmo{{ SHLIB_EXT }}   # [not win]
    - $PYTHON ${PREFIX}/share/numcosmo-{{ version }}/examples/example_simple.py

about:
  home: https://numcosmo.github.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'NumCosmo is a free software C library whose main purposes are to test cosmological models using observational data and to provide a set of tools to perform cosmological calculations.'

extra:
  recipe-maintainers:
    - vitenti
