{% set name = "numcosmo" %}
{% set version = "0.24.0" %}
{% set build = 0 %}
{% set sha256 = "15c395aa249a5652109400a00e3fae167971d18b24005c068c649596c9750f6e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NumCosmo/NumCosmo/releases/download/v{{ version }}/numcosmo-{{ version }}.tar.xz
  sha256: {{ sha256 }}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}

# prioritize nompi variant via build number
{% set build = build + 100 %}
{% endif %}

build:
  number: {{ build }}
  skip: true  # [py<310 or win or (python_impl=='pypy')]
{% if mpi != 'nompi' %}
{% set mpi_prefix = "mpi_" + mpi %}
{% else %}
{% set mpi_prefix = "nompi" %}
{% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
{% if mpi != 'nompi' %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
{% endif %}
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - meson
    - ninja
    - pkg-config
    - pytest
    - pytest-lazy-fixtures
    - pip
    - pygobject
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    - gobject-introspection
    - {{ mpi }}              # [build_platform != target_platform and mpi != 'nompi']
    - libfabric-devel        # [build_platform != target_platform and mpi != 'nompi']
    - libblas                # [build_platform != target_platform]
    - libcblas               # [build_platform != target_platform]
    - liblapack              # [build_platform != target_platform]
    - glib                   # [build_platform != target_platform]
    - gsl                    # [build_platform != target_platform]
    - gmp                    # [build_platform != target_platform]
    - mpfr                   # [build_platform != target_platform]
    - fftw                   # [build_platform != target_platform]
    - nlopt                  # [build_platform != target_platform]
    - cfitsio                # [build_platform != target_platform]
    - arb                    # [build_platform != target_platform]
    - hdf5                   # [build_platform != target_platform]
    - libfyaml               # [build_platform != target_platform]
    - zlib                   # [build_platform != target_platform]
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - libfabric-devel  # [mpi != 'nompi']
    - libblas
    - libcblas
    - liblapack
    - glib
    - gsl
    - gmp
    - mpfr
    - fftw
    - nlopt
    - cfitsio
    - arb
    - hdf5
    - libfyaml
    - python
    - pytest
    - pytest-lazy-fixtures
    - pygobject
    - zlib
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - libcurl
    - fftw
    - nlopt
    - cfitsio
    - pygobject
    - gobject-introspection
    - numpy
    - matplotlib-base
    - python
    - rich
    - typer
    - zlib

test:
  requires:
    - pygobject
    - openssh  # [mpi == 'openmpi']
  commands:
    - test -f ${PREFIX}/lib/libnumcosmo{{ SHLIB_EXT }}   # [not win]
    - $PYTHON ${PREFIX}/share/numcosmo-{{ version }}/examples/example_simple.py

about:
  home: https://numcosmo.github.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'NumCosmo is a free software C library whose main purposes are to test cosmological models using observational data and to provide a set of tools to perform cosmological calculations.'

extra:
  recipe-maintainers:
    - vitenti
