travis:
  secure:
    BINSTAR_TOKEN: raNe9NZQOLXx99nrRtM5lEF6vvAsDGIwjLeXdi1hmxVFgUnBL3TqlPZCxNxGZlnKHsbMzxAgg4MAsqmP+sG2QUM5RdRnRc6zQiTvr8mLggbzv+ZMU2+fcwdMMHd4EA145x8IfU+DJDEy0b4nhkD3acKq7FN4rGEmWN4byAOGLZp/4zkPEn6NWUHpUPnAXr1DWO6VtWBwQce/sJfyY/vx2MjYpujhspu681uaxB0/9HF4lGNsDH/NfKgXapAT9cL+bunEpBe0yi7ug5noqHjrVCy6j0FPnMGLEWx08ThrWv7uKZFzBY3l2BOXlv744LqV5Vo9XtRdtueygdjQw6iaJcC+ZUH88en92z6V/Z7vc38+aiZSuvRXj/E+XTZCzLil3QQwxcseEUKiq5Ft703FQlCxPEhx97Mekh+n7pV1is/zKwgJsZY0tdfNWyENr9e4OIsMpXjhpFH0PmYGvjlbFOTstgMeJ50nw2uQ+RzEdeJt3SNOsuFawxAODnY/xDkNpcovKzbaoPSOjPoXhQEJUfNaDkttmkXKWuLsgtV2Yg7VjUxXK4Z+m6+6AjWAlXqj+9/qrwm5DOWiYos4U7MuANVj/7bjbTetPcGI9QqpX/YMy0Zhn2vmAlL30gAbZwEBkxGRaAO2xkE7OZDwGw5A2wHegVrFiBzV8uo5kU6gx+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
